version: "3.8"
services:
  patchnetvlad:
    container_name: patchnetvlad
    image: phatli/patchnetvlad:latest
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./
        target: /home/user/patch-netvlad
